### ISSUE TITLE
Workflow for CSD -> HTML -> PDF

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#26]
- [ ] paginated HTML styling (allows print-to-PDF)
- [ ] implement new HTML print stylesheet in CSD

**Comment by opoudjis** [comment]
Investigate capabilities of prawn

Investigate html > pdf gems

**Comment by opoudjis** [comment]
I've done this, though it is creaky:

* The print CSS has been folded in to the HTML CSS as `@media print`
* It depends on the node library https://github.com/GoogleChrome/puppeteer
* I've given instructions on installation in the CSD readme that _need to be looked over by someone more familiar with Node_; particularly because I suggest installing puppeteer globally
* The same look-over is needed for the puppeteer invocations:

````
def pdf_convert(filename)
  url = "#{Dir.pwd}/#{filename}.html"
  pdfjs = File.join(File.dirname(__FILE__), 'pdf.js')
  system "export NODE_PATH=$(npm root --quiet -g); # use globally installed libraries
  node #{pdfjs} file://#{url} #{filename}.pdf"
end
````

This uses a command-line dependency on node, which is clunky: cf. https://www.forsbergplustwo.com/blogs/news/pdf-generation-with-chrome-headless-in-ruby-using-puppeteer-on-heroku

There is what purports to be a Ruby wrapper around puppeteer in https://github.com/tomasc/dragonfly_puppeteer . But (a) I couldn't get it to work; (b) I'm pretty sure the gem does not install any Node, and you have to do that yourself anyway; (c) dragonfly is utter overkill for what we're doing (and I couldn't work out how to use it anyway).

OTOH, Headless Chrome is widely hailed as much more robust than the other alternatives out there, including PhantomJS and wkhtmltopdf. The puppeteer library (which comes from Google) bundles Chromium, so you don't need to go hunting for a Chrome instance.

And the PDF looks great. Much better than Print To PDF from within Chrome, in face.

**Comment by wsdwl** [comment]
@ronaldtse : How will this end up in the version I am using for the bcp?

**Comment by opoudjis** [comment]
Apologies: what is the BCP?

As it stands, the gem now generates a PDF counterpart to the HTML page; there is print-specific styling in place in the HTML stylesheet, which puts the ToC up top, and imposes margins. I'm attaching what the PDF for RFC6350 looks like. 

[rfc6350.pdf](https://github.com/riboseinc/asciidoctor-csd/files/2063038/rfc6350.pdf)

**Comment by wsdwl** [comment]
BCP -> best common practice document, that I am writing with asciidoc for CalConnect. Ron suggested us, using asciidoc and copied the needed files to our repository (which is private, so you can't reach it in the moment).

**Comment by ronaldtse** [comment]
@opoudjis the "BCP" is @wsdwl's document in TC-CALSPAM.

@wsdwl sorry for the delay -- in order to update the versions in the BCP document, just run `bundle update` in there. I actually was holding up this reply because I needed to updated one more gem before we get the whole flow complete, give me a day for my colleague to reply... Thanks

**Comment by wsdwl** [comment]
BCP -> best common practice document, that I am writing with asciidoc for CalConnect. Ron suggested us, using asciidoc and copied the needed files to our repository (which is private, so you can't reach it in the moment).

**Comment by wsdwl** [comment]
Thanks! I tried that yesterday, but it wasn't ready.

I did it now, and the pdf wasn't generated. There is a new error at the end of the output of the make script:
wrong number of arguments (given 4, expected 3)
  Use --trace for backtrace
make: *** [csd-bp_calendarspam.html] Error 1

**Comment by wsdwl** [comment]
I did:
LMKA-MM8A01DTY3:BP_workingdraft ts$ gem install puppeteer
Fetching: puppeteer-0.0.1.gem (100%)
Successfully installed puppeteer-0.0.1
Parsing documentation for puppeteer-0.0.1
Installing ri documentation for puppeteer-0.0.1
Done installing documentation for puppeteer after 0 seconds
1 gem installed
LMKA-MM8A01DTY3:BP_workingdraft ts$ make clean all
....
rm: csd-bp_calendarspam_files/*: No such file or directory
wrong number of arguments (given 4, expected 3)
  Use --trace for backtrace
make: *** [csd-bp_calendarspam.html] Error 1

but it still didn't changed.

**Comment by ronaldtse** [comment]
@wsdwl give me couple minutes to fix this. 

In any case, Puppeteer needs to be installed like this:
https://github.com/riboseinc/asciidoctor-csd/#pdf-output

**Comment by ronaldtse** [comment]
I've pushed! It works now, I've switch to using the development versions.

Let me come up with an INSTALL flow and ping you.

**Comment by wsdwl** [comment]
That's fine for me and many thanks for doing this.

Any chance, that https://asciidoctor.org/docs/asciidoctor-pdf/ could be useful?

**Comment by ronaldtse** [comment]
This gem is quite complicated and is somewhat not ideal for the structure we're trying to achieve. We will at one point transition to a pure PDF rendering method, but it will take some (maybe a lot of) time.

**Comment by ronaldtse** [comment]
Cleaned-up the Gemfile too. Let me know if you run into any problems!

**Comment by wsdwl** [comment]
I followed all the install instructions and it worked! The pdf looks very nice!
